import { ORG_ID } from './constants';

// ============================================================
// CITYWISE FUNNEL QUERY - Locked Logic v9
// MTD till today, compare FTD vs yesterday (same period)
// Excludes Air Ambulance, Test orders
// Revenue in Lakhs (paise / 10,000,000)
// ============================================================
export function buildFunnelQuery(mtdStart, mtdEnd, today, yesterday, currentISTTime) {
  return `
WITH base AS (
  SELECT
    CASE WHEN n.SITE_TYPE_DESC = 'DIGITAL' THEN 'DIGITAL' ELSE UPPER(TRIM(n.CITY)) END AS CITY,
    CASE
      WHEN n.SITE_TYPE_DESC = 'DIGITAL' THEN 'Digital'
      WHEN n.SITE_TYPE_DESC = 'CORPORATE' THEN 'Stan Command'
      WHEN eu.USER_TYPE != 'CC_AGENT' THEN 'Hospital'
      ELSE 'Stan Command'
    END AS LOB,
    DATE(CONVERT_TIMEZONE('UTC','Asia/Kolkata',bo.META_CREATED_AT_TIMESTAMP)) AS created_date,
    TIME(CONVERT_TIMEZONE('UTC','Asia/Kolkata',bo.META_CREATED_AT_TIMESTAMP)) AS created_time,
    bo.ORDER_ID, bo.META_ORDER_TYPE, bo.META_ORDER_STATUS,
    bo.META_IS_FREE_TRIP, bo.PAYMENTS_TOTAL_ORDER_AMOUNT,
    bo.PAYMENTS_MARGIN, bo.DIGITAL_CUSTOMER_PAYMENT_AMOUNT,
    bo.META_IS_BILL_TO_PATIENT, bo.ASSIGNMENT_PROVIDER_TYPE,
    bo.META_SERVICEDETAILS_SERVICETYPE, v.bm_model_type
  FROM BLADE.CORE.RED_BLADE_ORDERS_FINAL bo
  LEFT JOIN BLADE.CORE.BLADE_VEHICLES_DATA v ON v.vehicle_id = bo.assignment_ambulance_id
  LEFT JOIN BLADE.CORE.BLADE_ORGANIZATION_ENTITIES_NEW_FLATTENED n
    ON bo.META_SITE_ID = n.SITE_ID
  LEFT JOIN (
    SELECT email, user_type
    FROM BLADE.CORE.BLADE_USER_ENTITIES_PARSED
    QUALIFY ROW_NUMBER() OVER (PARTITION BY email ORDER BY created_at DESC) = 1
  ) eu ON COALESCE(
    NULLIF(bo.META_BOOKING_CREATED_BY,''),
    NULLIF(bo.META_ENQUIRY_CREATED_BY,''),
    bo.META_CREATED_BY
  ) = eu.EMAIL
  WHERE bo.META_ORG_ID = '${ORG_ID}'
    AND COALESCE(bo.META_ORDER_TYPE,'') != 'TEST'
    AND IFNULL(bo.META_SERVICEDETAILS_SERVICETYPE,'') NOT IN ('AIR_AMBULANCE','DEAD_BODY_AIR_CARGO')
    AND (n.SITE_TYPE_DESC = 'DIGITAL' OR UPPER(TRIM(n.CITY)) IS NOT NULL)
    AND DATE(CONVERT_TIMEZONE('UTC','Asia/Kolkata',bo.META_CREATED_AT_TIMESTAMP))
        BETWEEN '${mtdStart}' AND '${mtdEnd}'
)
SELECT
  CITY, LOB,
  SUM(CASE WHEN META_ORDER_TYPE IN ('ENQUIRY','BOOKING') THEN 1 ELSE 0 END) AS MTD_ENQUIRY,
  SUM(CASE WHEN META_ORDER_TYPE = 'BOOKING' THEN 1 ELSE 0 END) AS MTD_BOOKING,
  SUM(CASE WHEN META_ORDER_TYPE = 'BOOKING' AND META_ORDER_STATUS IN ('IN_PROGRESS','COMPLETED') THEN 1 ELSE 0 END) AS MTD_TRIP,
  SUM(CASE WHEN META_ORDER_TYPE = 'BOOKING' AND META_ORDER_STATUS = 'COMPLETED' THEN 1 ELSE 0 END) AS MTD_TRIP_COMP,
  ROUND(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
    THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0) ELSE 0 END)/10000000,2) AS MTD_REV_BKD_L,
  ROUND(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND META_ORDER_STATUS IN('CANCELLED','DISPUTED')
    AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
    THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0) ELSE 0 END)/10000000,2) AS MTD_REV_CAN_L,
  ROUND(
    SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND META_ORDER_STATUS IN('CANCELLED','DISPUTED')
      AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0) ELSE 0 END)
    / NULLIF(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
      THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0) ELSE 0 END),0)*100, 1) AS MTD_CANCEL_PCT,
  ROUND(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' THEN 1 ELSE 0 END)*100.0
    / NULLIF(SUM(CASE WHEN META_ORDER_TYPE IN('ENQUIRY','BOOKING') THEN 1 ELSE 0 END),0), 1) AS MTD_BKG_CONV_PCT,
  ROUND(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND META_ORDER_STATUS='COMPLETED' THEN 1 ELSE 0 END)*100.0
    / NULLIF(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' THEN 1 ELSE 0 END),0), 1) AS MTD_TRIP_COMP_PCT,
  -- Funnel-based Performance Parameters (by booking/creation date)
  -- Margin %: margin on non-owned vehicles / non-owned revenue
  ROUND(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND ASSIGNMENT_PROVIDER_TYPE!='OWNED'
    THEN PAYMENTS_MARGIN/100 END), 0) AS MTD_F_MARGIN_AMT,
  ROUND(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND ASSIGNMENT_PROVIDER_TYPE!='OWNED'
    AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
    THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END),0) AS MTD_F_NON_OWN_REV,
  ROUND(
    SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND ASSIGNMENT_PROVIDER_TYPE!='OWNED' THEN PAYMENTS_MARGIN/100 END)
    / NULLIF(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND ASSIGNMENT_PROVIDER_TYPE!='OWNED'
      AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
      THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END),0)*100, 1) AS MTD_F_MARGIN_PCT,
  -- DQR %: digital payment / eligible B2P revenue
  ROUND(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND META_IS_BILL_TO_PATIENT=TRUE
    AND PAYMENTS_TOTAL_ORDER_AMOUNT>100 AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
    THEN IFNULL(DIGITAL_CUSTOMER_PAYMENT_AMOUNT,0)/100 END), 0) AS MTD_F_DQR,
  ROUND(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND META_IS_BILL_TO_PATIENT=TRUE
    AND PAYMENTS_TOTAL_ORDER_AMOUNT>100 AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
    THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 END), 0) AS MTD_F_DQR_DENOM,
  ROUND(
    SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND META_IS_BILL_TO_PATIENT=TRUE
      AND PAYMENTS_TOTAL_ORDER_AMOUNT>100 AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
      THEN IFNULL(DIGITAL_CUSTOMER_PAYMENT_AMOUNT,0)/100 END)
    / NULLIF(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND META_IS_BILL_TO_PATIENT=TRUE
      AND PAYMENTS_TOTAL_ORDER_AMOUNT>100 AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
      THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 END),0)*100, 1) AS MTD_F_DQR_PCT,
  -- Own Vehicle %: own-vehicle road revenue / total road revenue
  ROUND(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND bm_model_type='OWNED'
    AND META_SERVICEDETAILS_SERVICETYPE IN('ROAD_AMBULANCE','DEAD_BODY_ROAD_TRANSPORT')
    AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
    THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END),0) AS MTD_F_OWN_ROAD_REV,
  ROUND(SUM(CASE WHEN META_ORDER_TYPE='BOOKING'
    AND META_SERVICEDETAILS_SERVICETYPE IN('ROAD_AMBULANCE','DEAD_BODY_ROAD_TRANSPORT')
    AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
    THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END),0) AS MTD_F_ROAD_REV,
  ROUND(
    SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND bm_model_type='OWNED'
      AND META_SERVICEDETAILS_SERVICETYPE IN('ROAD_AMBULANCE','DEAD_BODY_ROAD_TRANSPORT')
      AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
      THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END)
    / NULLIF(SUM(CASE WHEN META_ORDER_TYPE='BOOKING'
      AND META_SERVICEDETAILS_SERVICETYPE IN('ROAD_AMBULANCE','DEAD_BODY_ROAD_TRANSPORT')
      AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
      THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END),0)*100, 1) AS MTD_F_OWN_ROAD_PCT,
  -- FTD (Today)
  SUM(CASE WHEN created_date='${today}' AND META_ORDER_TYPE IN('ENQUIRY','BOOKING') THEN 1 ELSE 0 END) AS TODAY_ENQUIRY,
  SUM(CASE WHEN created_date='${today}' AND META_ORDER_TYPE='BOOKING' THEN 1 ELSE 0 END) AS TODAY_BOOKING,
  SUM(CASE WHEN created_date='${today}' AND META_ORDER_TYPE='BOOKING' AND META_ORDER_STATUS='COMPLETED' THEN 1 ELSE 0 END) AS TODAY_TRIP_COMP,
  ROUND(SUM(CASE WHEN created_date='${today}' AND META_ORDER_TYPE='BOOKING' AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
    THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0) ELSE 0 END)/10000000,2) AS TODAY_REV_BKD_L,
  -- Yesterday (same period — capped at current IST time)
  SUM(CASE WHEN created_date='${yesterday}' AND created_time<='${currentISTTime}' AND META_ORDER_TYPE IN('ENQUIRY','BOOKING') THEN 1 ELSE 0 END) AS YDAY_ENQUIRY,
  SUM(CASE WHEN created_date='${yesterday}' AND created_time<='${currentISTTime}' AND META_ORDER_TYPE='BOOKING' THEN 1 ELSE 0 END) AS YDAY_BOOKING,
  SUM(CASE WHEN created_date='${yesterday}' AND created_time<='${currentISTTime}' AND META_ORDER_TYPE='BOOKING' AND META_ORDER_STATUS='COMPLETED' THEN 1 ELSE 0 END) AS YDAY_TRIP_COMP,
  ROUND(SUM(CASE WHEN created_date='${yesterday}' AND created_time<='${currentISTTime}' AND META_ORDER_TYPE='BOOKING' AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
    THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0) ELSE 0 END)/10000000,2) AS YDAY_REV_BKD_L
FROM base
GROUP BY CITY, LOB
ORDER BY MTD_REV_BKD_L DESC NULLS LAST`;
}

// ============================================================
// CITYWISE FINANCE QUERY - Locked Logic v9
// MTD till today, compare FTD vs yesterday (same period)
// Excludes Air Ambulance (DEAD_BODY_AIR_CARGO included)
// Revenue in Rupees (paise / 100)
// ============================================================
export function buildFinanceQuery(mtdStart, mtdEnd, today, yesterday, currentISTTime) {
  return `
WITH base AS (
  SELECT
    CASE WHEN n.SITE_TYPE_DESC = 'DIGITAL' THEN 'DIGITAL' ELSE UPPER(TRIM(n.CITY)) END AS CITY,
    CASE
      WHEN n.SITE_TYPE_DESC = 'DIGITAL' THEN 'Digital'
      WHEN n.SITE_TYPE_DESC = 'CORPORATE' THEN 'Stan Command'
      WHEN eu.user_type != 'CC_AGENT' THEN 'Hospital'
      ELSE 'Stan Command'
    END AS LOB,
    COALESCE(
      TO_DATE(CONVERT_TIMEZONE('UTC','Asia/Kolkata', f.assignment_reacheddropoffat_timestamp)),
      TO_DATE(f.FULFILLMENT_FULFILLED_AT_IST)
    ) AS fin_date,
    TIME(COALESCE(
      CONVERT_TIMEZONE('UTC','Asia/Kolkata', f.assignment_reacheddropoffat_timestamp),
      f.FULFILLMENT_FULFILLED_AT_IST
    )) AS fin_time,
    DATE_TRUNC('month', COALESCE(
      TO_DATE(CONVERT_TIMEZONE('UTC','Asia/Kolkata', f.assignment_reacheddropoffat_timestamp)),
      TO_DATE(f.FULFILLMENT_FULFILLED_AT_IST)
    )) AS fin_month,
    DATE_TRUNC('month', DATE(CONVERT_TIMEZONE('UTC','Asia/Kolkata', f.META_CREATED_AT_TIMESTAMP))) AS created_month,
    f.order_id, f.META_IS_FREE_TRIP, f.META_IS_BILL_TO_PATIENT,
    f.PAYMENTS_TOTAL_ORDER_AMOUNT, f.PAYMENTS_MARGIN, f.PAYMENTS_TOTAL_DISCOUNT,
    f.DIGITAL_CUSTOMER_PAYMENT_AMOUNT, f.ASSIGNMENT_PROVIDER_TYPE,
    f.META_SERVICEDETAILS_SERVICETYPE, v.bm_model_type
  FROM BLADE.CORE.RED_BLADE_ORDERS_FINAL f
  LEFT JOIN BLADE.CORE.BLADE_VEHICLES_DATA v ON v.vehicle_id = f.assignment_ambulance_id
  LEFT JOIN BLADE.CORE.BLADE_ORGANIZATION_ENTITIES_NEW_FLATTENED n ON f.meta_site_id = n.site_id
  LEFT JOIN (
    SELECT email, user_type FROM BLADE.CORE.BLADE_USER_ENTITIES_PARSED
    QUALIFY ROW_NUMBER() OVER (PARTITION BY email ORDER BY created_at DESC) = 1
  ) eu ON eu.email = f.META_BOOKING_CREATED_BY
  WHERE f.META_ORG_ID = '${ORG_ID}'
    AND f.META_ORDER_STATUS NOT IN ('CANCELLED','DISPUTED')
    AND f.META_ORDER_TYPE = 'BOOKING'
    AND IFNULL(f.meta_servicedetails_servicetype,'') != 'AIR_AMBULANCE'
    AND COALESCE(f.META_ORDER_TYPE,'') != 'TEST'
    AND (n.SITE_TYPE_DESC = 'DIGITAL' OR UPPER(TRIM(n.CITY)) IS NOT NULL)
    AND COALESCE(
      TO_DATE(CONVERT_TIMEZONE('UTC','Asia/Kolkata', f.assignment_reacheddropoffat_timestamp)),
      TO_DATE(f.FULFILLMENT_FULFILLED_AT_IST)
    ) BETWEEN '${mtdStart}' AND '${mtdEnd}'
)
SELECT
  CITY, LOB,
  COUNT(order_id) AS MTD_TRIPS_DELIVERED,
  ROUND(SUM(CASE WHEN IFNULL(META_IS_FREE_TRIP,FALSE)=TRUE THEN 0 ELSE IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 END), 0) AS MTD_REV,
  ROUND(SUM(CASE WHEN ASSIGNMENT_PROVIDER_TYPE!='OWNED' THEN PAYMENTS_MARGIN/100 END), 0) AS MTD_MARGIN_AMT,
  ROUND(SUM(CASE WHEN ASSIGNMENT_PROVIDER_TYPE!='OWNED' AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
    THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END),0) AS MTD_NON_OWN_REV,
  ROUND(
    SUM(CASE WHEN ASSIGNMENT_PROVIDER_TYPE!='OWNED' THEN PAYMENTS_MARGIN/100 END)
    / NULLIF(SUM(CASE WHEN ASSIGNMENT_PROVIDER_TYPE!='OWNED' AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
      THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END),0)*100, 1) AS MTD_MARGIN_PCT,
  ROUND(SUM(CASE WHEN META_IS_BILL_TO_PATIENT=TRUE AND PAYMENTS_TOTAL_ORDER_AMOUNT>100
    AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE THEN IFNULL(DIGITAL_CUSTOMER_PAYMENT_AMOUNT,0)/100 END), 0) AS MTD_DQR,
  ROUND(
    SUM(CASE WHEN META_IS_BILL_TO_PATIENT=TRUE AND PAYMENTS_TOTAL_ORDER_AMOUNT>100
      AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE THEN IFNULL(DIGITAL_CUSTOMER_PAYMENT_AMOUNT,0)/100 END)
    / NULLIF(SUM(CASE WHEN IFNULL(META_IS_FREE_TRIP,FALSE)=TRUE THEN 0 ELSE IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 END),0)*100, 1) AS MTD_DQR_PCT,
  ROUND(SUM(CASE WHEN bm_model_type='OWNED' AND META_SERVICEDETAILS_SERVICETYPE IN('ROAD_AMBULANCE','DEAD_BODY_ROAD_TRANSPORT')
    AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END),0) AS MTD_OWN_ROAD_REV,
  ROUND(SUM(CASE WHEN META_SERVICEDETAILS_SERVICETYPE IN('ROAD_AMBULANCE','DEAD_BODY_ROAD_TRANSPORT')
    AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END),0) AS MTD_ROAD_REV,
  ROUND(
    SUM(CASE WHEN bm_model_type='OWNED' AND META_SERVICEDETAILS_SERVICETYPE IN('ROAD_AMBULANCE','DEAD_BODY_ROAD_TRANSPORT')
      AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END)
    / NULLIF(SUM(CASE WHEN META_SERVICEDETAILS_SERVICETYPE IN('ROAD_AMBULANCE','DEAD_BODY_ROAD_TRANSPORT')
      AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END),0)*100, 1) AS MTD_OWN_ROAD_PCT,
  COUNT(CASE WHEN fin_date='${today}' THEN order_id END) AS TODAY_TRIPS,
  ROUND(SUM(CASE WHEN fin_date='${today}' THEN CASE WHEN IFNULL(META_IS_FREE_TRIP,FALSE)=TRUE THEN 0
    ELSE IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 END ELSE 0 END),0) AS TODAY_REV,
  COUNT(CASE WHEN fin_date='${yesterday}' AND fin_time<='${currentISTTime}' THEN order_id END) AS YDAY_TRIPS,
  ROUND(SUM(CASE WHEN fin_date='${yesterday}' AND fin_time<='${currentISTTime}' THEN CASE WHEN IFNULL(META_IS_FREE_TRIP,FALSE)=TRUE THEN 0
    ELSE IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 END ELSE 0 END),0) AS YDAY_REV
FROM base
GROUP BY CITY, LOB
ORDER BY MTD_REV DESC NULLS LAST`;
}

// ============================================================
// HOSPITAL-WISE FUNNEL QUERY - Locked Logic v9
// MTD till today, compare FTD vs yesterday (same period)
// Groups by CITY + HOSPITAL (site name)
// ============================================================
export function buildHospitalQuery(mtdStart, mtdEnd, today, yesterday, currentISTTime) {
  return `
WITH base AS (
  SELECT
    CASE WHEN n.SITE_TYPE_DESC = 'DIGITAL' THEN 'DIGITAL' ELSE UPPER(TRIM(n.CITY)) END AS CITY,
    COALESCE(NULLIF(TRIM(n.NAME),''), 'Unknown Hospital') AS HOSPITAL,
    CASE
      WHEN n.SITE_TYPE_DESC = 'DIGITAL' THEN 'Digital'
      WHEN n.SITE_TYPE_DESC = 'CORPORATE' THEN 'Stan Command'
      ELSE 'Hospital'
    END AS LOB,
    DATE(CONVERT_TIMEZONE('UTC','Asia/Kolkata',bo.META_CREATED_AT_TIMESTAMP)) AS created_date,
    TIME(CONVERT_TIMEZONE('UTC','Asia/Kolkata',bo.META_CREATED_AT_TIMESTAMP)) AS created_time,
    bo.ORDER_ID, bo.META_ORDER_TYPE, bo.META_ORDER_STATUS,
    bo.META_IS_FREE_TRIP, bo.PAYMENTS_TOTAL_ORDER_AMOUNT,
    bo.PAYMENTS_MARGIN, bo.DIGITAL_CUSTOMER_PAYMENT_AMOUNT,
    bo.META_IS_BILL_TO_PATIENT, bo.ASSIGNMENT_PROVIDER_TYPE,
    bo.META_SERVICEDETAILS_SERVICETYPE, v.bm_model_type
  FROM BLADE.CORE.RED_BLADE_ORDERS_FINAL bo
  LEFT JOIN BLADE.CORE.BLADE_VEHICLES_DATA v ON v.vehicle_id = bo.assignment_ambulance_id
  LEFT JOIN BLADE.CORE.BLADE_ORGANIZATION_ENTITIES_NEW_FLATTENED n
    ON bo.META_SITE_ID = n.SITE_ID
  WHERE bo.META_ORG_ID = '${ORG_ID}'
    AND COALESCE(bo.META_ORDER_TYPE,'') != 'TEST'
    AND IFNULL(bo.META_SERVICEDETAILS_SERVICETYPE,'') NOT IN ('AIR_AMBULANCE','DEAD_BODY_AIR_CARGO')
    AND (n.SITE_TYPE_DESC = 'DIGITAL' OR UPPER(TRIM(n.CITY)) IS NOT NULL)
    AND DATE(CONVERT_TIMEZONE('UTC','Asia/Kolkata',bo.META_CREATED_AT_TIMESTAMP))
        BETWEEN '${mtdStart}' AND '${mtdEnd}'
)
SELECT
  CITY,
  HOSPITAL,
  LOB,
  SUM(CASE WHEN META_ORDER_TYPE IN ('ENQUIRY','BOOKING') THEN 1 ELSE 0 END) AS MTD_ENQUIRY,
  SUM(CASE WHEN META_ORDER_TYPE = 'BOOKING' THEN 1 ELSE 0 END) AS MTD_BOOKING,
  SUM(CASE WHEN META_ORDER_TYPE = 'BOOKING' AND META_ORDER_STATUS = 'COMPLETED' THEN 1 ELSE 0 END) AS MTD_TRIP_COMP,
  ROUND(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
    THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0) ELSE 0 END)/10000000,2) AS MTD_REV_BKD_L,
  ROUND(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND META_ORDER_STATUS IN('CANCELLED','DISPUTED')
    AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
    THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0) ELSE 0 END)/10000000,2) AS MTD_REV_CAN_L,
  ROUND(
    SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND META_ORDER_STATUS IN('CANCELLED','DISPUTED')
      AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0) ELSE 0 END)
    / NULLIF(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
      THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0) ELSE 0 END),0)*100, 1) AS MTD_CANCEL_PCT,
  ROUND(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' THEN 1 ELSE 0 END)*100.0
    / NULLIF(SUM(CASE WHEN META_ORDER_TYPE IN('ENQUIRY','BOOKING') THEN 1 ELSE 0 END),0), 1) AS MTD_BKG_CONV_PCT,
  ROUND(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND META_ORDER_STATUS='COMPLETED' THEN 1 ELSE 0 END)*100.0
    / NULLIF(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' THEN 1 ELSE 0 END),0), 1) AS MTD_TRIP_COMP_PCT,
  -- Funnel-based Performance Parameters
  ROUND(
    SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND ASSIGNMENT_PROVIDER_TYPE!='OWNED' THEN PAYMENTS_MARGIN/100 END)
    / NULLIF(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND ASSIGNMENT_PROVIDER_TYPE!='OWNED'
      AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
      THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END),0)*100, 1) AS MTD_F_MARGIN_PCT,
  ROUND(
    SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND META_IS_BILL_TO_PATIENT=TRUE
      AND PAYMENTS_TOTAL_ORDER_AMOUNT>100 AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
      THEN IFNULL(DIGITAL_CUSTOMER_PAYMENT_AMOUNT,0)/100 END)
    / NULLIF(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND META_IS_BILL_TO_PATIENT=TRUE
      AND PAYMENTS_TOTAL_ORDER_AMOUNT>100 AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
      THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 END),0)*100, 1) AS MTD_F_DQR_PCT,
  ROUND(
    SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND bm_model_type='OWNED'
      AND META_SERVICEDETAILS_SERVICETYPE IN('ROAD_AMBULANCE','DEAD_BODY_ROAD_TRANSPORT')
      AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
      THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END)
    / NULLIF(SUM(CASE WHEN META_ORDER_TYPE='BOOKING'
      AND META_SERVICEDETAILS_SERVICETYPE IN('ROAD_AMBULANCE','DEAD_BODY_ROAD_TRANSPORT')
      AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
      THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END),0)*100, 1) AS MTD_F_OWN_ROAD_PCT,
  ROUND(SUM(CASE WHEN META_ORDER_TYPE='BOOKING'
    AND META_SERVICEDETAILS_SERVICETYPE IN('ROAD_AMBULANCE','DEAD_BODY_ROAD_TRANSPORT')
    AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
    THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END),0) AS MTD_F_ROAD_REV,
  SUM(CASE WHEN created_date='${today}' AND META_ORDER_TYPE IN('ENQUIRY','BOOKING') THEN 1 ELSE 0 END) AS TODAY_ENQUIRY,
  SUM(CASE WHEN created_date='${today}' AND META_ORDER_TYPE='BOOKING' THEN 1 ELSE 0 END) AS TODAY_BOOKING,
  SUM(CASE WHEN created_date='${today}' AND META_ORDER_TYPE='BOOKING' AND META_ORDER_STATUS='COMPLETED' THEN 1 ELSE 0 END) AS TODAY_TRIP_COMP,
  ROUND(SUM(CASE WHEN created_date='${today}' AND META_ORDER_TYPE='BOOKING' AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
    THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0) ELSE 0 END)/10000000,2) AS TODAY_REV_BKD_L,
  SUM(CASE WHEN created_date='${yesterday}' AND created_time<='${currentISTTime}' AND META_ORDER_TYPE IN('ENQUIRY','BOOKING') THEN 1 ELSE 0 END) AS YDAY_ENQUIRY,
  SUM(CASE WHEN created_date='${yesterday}' AND created_time<='${currentISTTime}' AND META_ORDER_TYPE='BOOKING' THEN 1 ELSE 0 END) AS YDAY_BOOKING,
  SUM(CASE WHEN created_date='${yesterday}' AND created_time<='${currentISTTime}' AND META_ORDER_TYPE='BOOKING' AND META_ORDER_STATUS='COMPLETED' THEN 1 ELSE 0 END) AS YDAY_TRIP_COMP,
  ROUND(SUM(CASE WHEN created_date='${yesterday}' AND created_time<='${currentISTTime}' AND META_ORDER_TYPE='BOOKING' AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
    THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0) ELSE 0 END)/10000000,2) AS YDAY_REV_BKD_L
FROM base
GROUP BY CITY, HOSPITAL, LOB
HAVING MTD_BOOKING > 0
ORDER BY MTD_REV_BKD_L DESC NULLS LAST`;
}

// ============================================================
// AGENT-WISE FUNNEL QUERY - Locked Logic v9
// MTD till today, compare FTD vs yesterday (same period)
// Groups by CITY + AGENT (booking creator email)
// ============================================================
export function buildAgentQuery(mtdStart, mtdEnd, today, yesterday, currentISTTime) {
  return `
WITH base AS (
  SELECT
    CASE WHEN n.SITE_TYPE_DESC = 'DIGITAL' THEN 'DIGITAL' ELSE UPPER(TRIM(n.CITY)) END AS CITY,
    COALESCE(
      NULLIF(bo.META_BOOKING_CREATED_BY,''),
      NULLIF(bo.META_ENQUIRY_CREATED_BY,''),
      bo.META_CREATED_BY
    ) AS AGENT_EMAIL,
    CASE
      WHEN n.SITE_TYPE_DESC = 'DIGITAL' THEN 'Digital'
      WHEN n.SITE_TYPE_DESC = 'CORPORATE' THEN 'Stan Command'
      WHEN eu.USER_TYPE != 'CC_AGENT' THEN 'Hospital'
      ELSE 'Stan Command'
    END AS LOB,
    DATE(CONVERT_TIMEZONE('UTC','Asia/Kolkata',bo.META_CREATED_AT_TIMESTAMP)) AS created_date,
    TIME(CONVERT_TIMEZONE('UTC','Asia/Kolkata',bo.META_CREATED_AT_TIMESTAMP)) AS created_time,
    bo.ORDER_ID, bo.META_ORDER_TYPE, bo.META_ORDER_STATUS,
    bo.META_IS_FREE_TRIP, bo.PAYMENTS_TOTAL_ORDER_AMOUNT,
    bo.PAYMENTS_MARGIN, bo.DIGITAL_CUSTOMER_PAYMENT_AMOUNT,
    bo.META_IS_BILL_TO_PATIENT, bo.ASSIGNMENT_PROVIDER_TYPE,
    bo.META_SERVICEDETAILS_SERVICETYPE, v.bm_model_type
  FROM BLADE.CORE.RED_BLADE_ORDERS_FINAL bo
  LEFT JOIN BLADE.CORE.BLADE_VEHICLES_DATA v ON v.vehicle_id = bo.assignment_ambulance_id
  LEFT JOIN BLADE.CORE.BLADE_ORGANIZATION_ENTITIES_NEW_FLATTENED n
    ON bo.META_SITE_ID = n.SITE_ID
  LEFT JOIN (
    SELECT email, user_type
    FROM BLADE.CORE.BLADE_USER_ENTITIES_PARSED
    QUALIFY ROW_NUMBER() OVER (PARTITION BY email ORDER BY created_at DESC) = 1
  ) eu ON COALESCE(
    NULLIF(bo.META_BOOKING_CREATED_BY,''),
    NULLIF(bo.META_ENQUIRY_CREATED_BY,''),
    bo.META_CREATED_BY
  ) = eu.EMAIL
  WHERE bo.META_ORG_ID = '${ORG_ID}'
    AND COALESCE(bo.META_ORDER_TYPE,'') != 'TEST'
    AND IFNULL(bo.META_SERVICEDETAILS_SERVICETYPE,'') NOT IN ('AIR_AMBULANCE','DEAD_BODY_AIR_CARGO')
    AND (n.SITE_TYPE_DESC = 'DIGITAL' OR UPPER(TRIM(n.CITY)) IS NOT NULL)
    AND DATE(CONVERT_TIMEZONE('UTC','Asia/Kolkata',bo.META_CREATED_AT_TIMESTAMP))
        BETWEEN '${mtdStart}' AND '${mtdEnd}'
)
SELECT
  CITY,
  COALESCE(AGENT_EMAIL, 'Unknown') AS AGENT,
  LOB,
  SUM(CASE WHEN META_ORDER_TYPE IN ('ENQUIRY','BOOKING') THEN 1 ELSE 0 END) AS MTD_ENQUIRY,
  SUM(CASE WHEN META_ORDER_TYPE = 'BOOKING' THEN 1 ELSE 0 END) AS MTD_BOOKING,
  SUM(CASE WHEN META_ORDER_TYPE = 'BOOKING' AND META_ORDER_STATUS = 'COMPLETED' THEN 1 ELSE 0 END) AS MTD_TRIP_COMP,
  ROUND(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
    THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0) ELSE 0 END)/10000000,2) AS MTD_REV_BKD_L,
  ROUND(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND META_ORDER_STATUS IN('CANCELLED','DISPUTED')
    AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
    THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0) ELSE 0 END)/10000000,2) AS MTD_REV_CAN_L,
  ROUND(
    SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND META_ORDER_STATUS IN('CANCELLED','DISPUTED')
      AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0) ELSE 0 END)
    / NULLIF(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
      THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0) ELSE 0 END),0)*100, 1) AS MTD_CANCEL_PCT,
  ROUND(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' THEN 1 ELSE 0 END)*100.0
    / NULLIF(SUM(CASE WHEN META_ORDER_TYPE IN('ENQUIRY','BOOKING') THEN 1 ELSE 0 END),0), 1) AS MTD_BKG_CONV_PCT,
  ROUND(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND META_ORDER_STATUS='COMPLETED' THEN 1 ELSE 0 END)*100.0
    / NULLIF(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' THEN 1 ELSE 0 END),0), 1) AS MTD_TRIP_COMP_PCT,
  -- Funnel-based Performance Parameters
  ROUND(
    SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND ASSIGNMENT_PROVIDER_TYPE!='OWNED' THEN PAYMENTS_MARGIN/100 END)
    / NULLIF(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND ASSIGNMENT_PROVIDER_TYPE!='OWNED'
      AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
      THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END),0)*100, 1) AS MTD_F_MARGIN_PCT,
  ROUND(
    SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND META_IS_BILL_TO_PATIENT=TRUE
      AND PAYMENTS_TOTAL_ORDER_AMOUNT>100 AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
      THEN IFNULL(DIGITAL_CUSTOMER_PAYMENT_AMOUNT,0)/100 END)
    / NULLIF(SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND META_IS_BILL_TO_PATIENT=TRUE
      AND PAYMENTS_TOTAL_ORDER_AMOUNT>100 AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
      THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 END),0)*100, 1) AS MTD_F_DQR_PCT,
  ROUND(
    SUM(CASE WHEN META_ORDER_TYPE='BOOKING' AND bm_model_type='OWNED'
      AND META_SERVICEDETAILS_SERVICETYPE IN('ROAD_AMBULANCE','DEAD_BODY_ROAD_TRANSPORT')
      AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
      THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END)
    / NULLIF(SUM(CASE WHEN META_ORDER_TYPE='BOOKING'
      AND META_SERVICEDETAILS_SERVICETYPE IN('ROAD_AMBULANCE','DEAD_BODY_ROAD_TRANSPORT')
      AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
      THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END),0)*100, 1) AS MTD_F_OWN_ROAD_PCT,
  ROUND(SUM(CASE WHEN META_ORDER_TYPE='BOOKING'
    AND META_SERVICEDETAILS_SERVICETYPE IN('ROAD_AMBULANCE','DEAD_BODY_ROAD_TRANSPORT')
    AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
    THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END),0) AS MTD_F_ROAD_REV,
  SUM(CASE WHEN created_date='${today}' AND META_ORDER_TYPE IN('ENQUIRY','BOOKING') THEN 1 ELSE 0 END) AS TODAY_ENQUIRY,
  SUM(CASE WHEN created_date='${today}' AND META_ORDER_TYPE='BOOKING' THEN 1 ELSE 0 END) AS TODAY_BOOKING,
  SUM(CASE WHEN created_date='${today}' AND META_ORDER_TYPE='BOOKING' AND META_ORDER_STATUS='COMPLETED' THEN 1 ELSE 0 END) AS TODAY_TRIP_COMP,
  ROUND(SUM(CASE WHEN created_date='${today}' AND META_ORDER_TYPE='BOOKING' AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
    THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0) ELSE 0 END)/10000000,2) AS TODAY_REV_BKD_L,
  SUM(CASE WHEN created_date='${yesterday}' AND created_time<='${currentISTTime}' AND META_ORDER_TYPE IN('ENQUIRY','BOOKING') THEN 1 ELSE 0 END) AS YDAY_ENQUIRY,
  SUM(CASE WHEN created_date='${yesterday}' AND created_time<='${currentISTTime}' AND META_ORDER_TYPE='BOOKING' THEN 1 ELSE 0 END) AS YDAY_BOOKING,
  SUM(CASE WHEN created_date='${yesterday}' AND created_time<='${currentISTTime}' AND META_ORDER_TYPE='BOOKING' AND META_ORDER_STATUS='COMPLETED' THEN 1 ELSE 0 END) AS YDAY_TRIP_COMP,
  ROUND(SUM(CASE WHEN created_date='${yesterday}' AND created_time<='${currentISTTime}' AND META_ORDER_TYPE='BOOKING' AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
    THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0) ELSE 0 END)/10000000,2) AS YDAY_REV_BKD_L
FROM base
GROUP BY CITY, AGENT_EMAIL, LOB
HAVING MTD_BOOKING > 0
ORDER BY MTD_REV_BKD_L DESC NULLS LAST`;
}

// ============================================================
// HOSPITAL-WISE FINANCE QUERY
// Same KPIs as city-level finance, grouped by CITY + HOSPITAL
// ============================================================
export function buildHospitalFinanceQuery(mtdStart, mtdEnd, today, yesterday, currentISTTime) {
  return `
WITH base AS (
  SELECT
    CASE WHEN n.SITE_TYPE_DESC = 'DIGITAL' THEN 'DIGITAL' ELSE UPPER(TRIM(n.CITY)) END AS CITY,
    COALESCE(NULLIF(TRIM(n.NAME),''), 'Unknown Hospital') AS HOSPITAL,
    CASE
      WHEN n.SITE_TYPE_DESC = 'DIGITAL' THEN 'Digital'
      WHEN n.SITE_TYPE_DESC = 'CORPORATE' THEN 'Stan Command'
      ELSE 'Hospital'
    END AS LOB,
    COALESCE(
      TO_DATE(CONVERT_TIMEZONE('UTC','Asia/Kolkata', f.assignment_reacheddropoffat_timestamp)),
      TO_DATE(f.FULFILLMENT_FULFILLED_AT_IST)
    ) AS fin_date,
    TIME(COALESCE(
      CONVERT_TIMEZONE('UTC','Asia/Kolkata', f.assignment_reacheddropoffat_timestamp),
      f.FULFILLMENT_FULFILLED_AT_IST
    )) AS fin_time,
    f.order_id, f.META_IS_FREE_TRIP, f.META_IS_BILL_TO_PATIENT,
    f.PAYMENTS_TOTAL_ORDER_AMOUNT, f.PAYMENTS_MARGIN, f.PAYMENTS_TOTAL_DISCOUNT,
    f.DIGITAL_CUSTOMER_PAYMENT_AMOUNT, f.ASSIGNMENT_PROVIDER_TYPE,
    f.META_SERVICEDETAILS_SERVICETYPE, v.bm_model_type
  FROM BLADE.CORE.RED_BLADE_ORDERS_FINAL f
  LEFT JOIN BLADE.CORE.BLADE_VEHICLES_DATA v ON v.vehicle_id = f.assignment_ambulance_id
  LEFT JOIN BLADE.CORE.BLADE_ORGANIZATION_ENTITIES_NEW_FLATTENED n ON f.meta_site_id = n.site_id
  WHERE f.META_ORG_ID = '${ORG_ID}'
    AND f.META_ORDER_STATUS NOT IN ('CANCELLED','DISPUTED')
    AND f.META_ORDER_TYPE = 'BOOKING'
    AND IFNULL(f.meta_servicedetails_servicetype,'') != 'AIR_AMBULANCE'
    AND COALESCE(f.META_ORDER_TYPE,'') != 'TEST'
    AND (n.SITE_TYPE_DESC = 'DIGITAL' OR UPPER(TRIM(n.CITY)) IS NOT NULL)
    AND COALESCE(
      TO_DATE(CONVERT_TIMEZONE('UTC','Asia/Kolkata', f.assignment_reacheddropoffat_timestamp)),
      TO_DATE(f.FULFILLMENT_FULFILLED_AT_IST)
    ) BETWEEN '${mtdStart}' AND '${mtdEnd}'
)
SELECT
  CITY,
  HOSPITAL,
  LOB,
  COUNT(order_id) AS MTD_TRIPS_DELIVERED,
  ROUND(SUM(CASE WHEN IFNULL(META_IS_FREE_TRIP,FALSE)=TRUE THEN 0 ELSE IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 END), 0) AS MTD_REV,
  ROUND(SUM(CASE WHEN ASSIGNMENT_PROVIDER_TYPE!='OWNED' THEN PAYMENTS_MARGIN/100 END), 0) AS MTD_MARGIN_AMT,
  ROUND(SUM(CASE WHEN ASSIGNMENT_PROVIDER_TYPE!='OWNED' AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
    THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END),0) AS MTD_NON_OWN_REV,
  ROUND(
    SUM(CASE WHEN ASSIGNMENT_PROVIDER_TYPE!='OWNED' THEN PAYMENTS_MARGIN/100 END)
    / NULLIF(SUM(CASE WHEN ASSIGNMENT_PROVIDER_TYPE!='OWNED' AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
      THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END),0)*100, 1) AS MTD_MARGIN_PCT,
  ROUND(SUM(CASE WHEN META_IS_BILL_TO_PATIENT=TRUE AND PAYMENTS_TOTAL_ORDER_AMOUNT>100
    AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE THEN IFNULL(DIGITAL_CUSTOMER_PAYMENT_AMOUNT,0)/100 END), 0) AS MTD_DQR,
  ROUND(
    SUM(CASE WHEN META_IS_BILL_TO_PATIENT=TRUE AND PAYMENTS_TOTAL_ORDER_AMOUNT>100
      AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE THEN IFNULL(DIGITAL_CUSTOMER_PAYMENT_AMOUNT,0)/100 END)
    / NULLIF(SUM(CASE WHEN IFNULL(META_IS_FREE_TRIP,FALSE)=TRUE THEN 0 ELSE IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 END),0)*100, 1) AS MTD_DQR_PCT,
  ROUND(SUM(CASE WHEN bm_model_type='OWNED' AND META_SERVICEDETAILS_SERVICETYPE IN('ROAD_AMBULANCE','DEAD_BODY_ROAD_TRANSPORT')
    AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END),0) AS MTD_OWN_ROAD_REV,
  ROUND(SUM(CASE WHEN META_SERVICEDETAILS_SERVICETYPE IN('ROAD_AMBULANCE','DEAD_BODY_ROAD_TRANSPORT')
    AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END),0) AS MTD_ROAD_REV,
  ROUND(
    SUM(CASE WHEN bm_model_type='OWNED' AND META_SERVICEDETAILS_SERVICETYPE IN('ROAD_AMBULANCE','DEAD_BODY_ROAD_TRANSPORT')
      AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END)
    / NULLIF(SUM(CASE WHEN META_SERVICEDETAILS_SERVICETYPE IN('ROAD_AMBULANCE','DEAD_BODY_ROAD_TRANSPORT')
      AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END),0)*100, 1) AS MTD_OWN_ROAD_PCT,
  COUNT(CASE WHEN fin_date='${today}' THEN order_id END) AS TODAY_TRIPS,
  ROUND(SUM(CASE WHEN fin_date='${today}' THEN CASE WHEN IFNULL(META_IS_FREE_TRIP,FALSE)=TRUE THEN 0
    ELSE IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 END ELSE 0 END),0) AS TODAY_REV,
  COUNT(CASE WHEN fin_date='${yesterday}' AND fin_time<='${currentISTTime}' THEN order_id END) AS YDAY_TRIPS,
  ROUND(SUM(CASE WHEN fin_date='${yesterday}' AND fin_time<='${currentISTTime}' THEN CASE WHEN IFNULL(META_IS_FREE_TRIP,FALSE)=TRUE THEN 0
    ELSE IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 END ELSE 0 END),0) AS YDAY_REV
FROM base
GROUP BY CITY, HOSPITAL, LOB
HAVING MTD_TRIPS_DELIVERED > 0
ORDER BY MTD_REV DESC NULLS LAST`;
}

// ============================================================
// AGENT-WISE FINANCE QUERY
// Same KPIs as city-level finance, grouped by CITY + AGENT + LOB
// ============================================================
export function buildAgentFinanceQuery(mtdStart, mtdEnd, today, yesterday, currentISTTime) {
  return `
WITH base AS (
  SELECT
    CASE WHEN n.SITE_TYPE_DESC = 'DIGITAL' THEN 'DIGITAL' ELSE UPPER(TRIM(n.CITY)) END AS CITY,
    COALESCE(
      NULLIF(f.META_BOOKING_CREATED_BY,''),
      NULLIF(f.META_ENQUIRY_CREATED_BY,''),
      f.META_CREATED_BY
    ) AS AGENT_EMAIL,
    CASE
      WHEN n.SITE_TYPE_DESC = 'DIGITAL' THEN 'Digital'
      WHEN n.SITE_TYPE_DESC = 'CORPORATE' THEN 'Stan Command'
      WHEN eu.user_type != 'CC_AGENT' THEN 'Hospital'
      ELSE 'Stan Command'
    END AS LOB,
    COALESCE(
      TO_DATE(CONVERT_TIMEZONE('UTC','Asia/Kolkata', f.assignment_reacheddropoffat_timestamp)),
      TO_DATE(f.FULFILLMENT_FULFILLED_AT_IST)
    ) AS fin_date,
    TIME(COALESCE(
      CONVERT_TIMEZONE('UTC','Asia/Kolkata', f.assignment_reacheddropoffat_timestamp),
      f.FULFILLMENT_FULFILLED_AT_IST
    )) AS fin_time,
    f.order_id, f.META_IS_FREE_TRIP, f.META_IS_BILL_TO_PATIENT,
    f.PAYMENTS_TOTAL_ORDER_AMOUNT, f.PAYMENTS_MARGIN, f.PAYMENTS_TOTAL_DISCOUNT,
    f.DIGITAL_CUSTOMER_PAYMENT_AMOUNT, f.ASSIGNMENT_PROVIDER_TYPE,
    f.META_SERVICEDETAILS_SERVICETYPE, v.bm_model_type
  FROM BLADE.CORE.RED_BLADE_ORDERS_FINAL f
  LEFT JOIN BLADE.CORE.BLADE_VEHICLES_DATA v ON v.vehicle_id = f.assignment_ambulance_id
  LEFT JOIN BLADE.CORE.BLADE_ORGANIZATION_ENTITIES_NEW_FLATTENED n ON f.meta_site_id = n.site_id
  LEFT JOIN (
    SELECT email, user_type FROM BLADE.CORE.BLADE_USER_ENTITIES_PARSED
    QUALIFY ROW_NUMBER() OVER (PARTITION BY email ORDER BY created_at DESC) = 1
  ) eu ON eu.email = f.META_BOOKING_CREATED_BY
  WHERE f.META_ORG_ID = '${ORG_ID}'
    AND f.META_ORDER_STATUS NOT IN ('CANCELLED','DISPUTED')
    AND f.META_ORDER_TYPE = 'BOOKING'
    AND IFNULL(f.meta_servicedetails_servicetype,'') != 'AIR_AMBULANCE'
    AND COALESCE(f.META_ORDER_TYPE,'') != 'TEST'
    AND (n.SITE_TYPE_DESC = 'DIGITAL' OR UPPER(TRIM(n.CITY)) IS NOT NULL)
    AND COALESCE(
      TO_DATE(CONVERT_TIMEZONE('UTC','Asia/Kolkata', f.assignment_reacheddropoffat_timestamp)),
      TO_DATE(f.FULFILLMENT_FULFILLED_AT_IST)
    ) BETWEEN '${mtdStart}' AND '${mtdEnd}'
)
SELECT
  CITY,
  COALESCE(AGENT_EMAIL, 'Unknown') AS AGENT,
  LOB,
  COUNT(order_id) AS MTD_TRIPS_DELIVERED,
  ROUND(SUM(CASE WHEN IFNULL(META_IS_FREE_TRIP,FALSE)=TRUE THEN 0 ELSE IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 END), 0) AS MTD_REV,
  ROUND(SUM(CASE WHEN ASSIGNMENT_PROVIDER_TYPE!='OWNED' THEN PAYMENTS_MARGIN/100 END), 0) AS MTD_MARGIN_AMT,
  ROUND(SUM(CASE WHEN ASSIGNMENT_PROVIDER_TYPE!='OWNED' AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
    THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END),0) AS MTD_NON_OWN_REV,
  ROUND(
    SUM(CASE WHEN ASSIGNMENT_PROVIDER_TYPE!='OWNED' THEN PAYMENTS_MARGIN/100 END)
    / NULLIF(SUM(CASE WHEN ASSIGNMENT_PROVIDER_TYPE!='OWNED' AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE
      THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END),0)*100, 1) AS MTD_MARGIN_PCT,
  ROUND(SUM(CASE WHEN META_IS_BILL_TO_PATIENT=TRUE AND PAYMENTS_TOTAL_ORDER_AMOUNT>100
    AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE THEN IFNULL(DIGITAL_CUSTOMER_PAYMENT_AMOUNT,0)/100 END), 0) AS MTD_DQR,
  ROUND(
    SUM(CASE WHEN META_IS_BILL_TO_PATIENT=TRUE AND PAYMENTS_TOTAL_ORDER_AMOUNT>100
      AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE THEN IFNULL(DIGITAL_CUSTOMER_PAYMENT_AMOUNT,0)/100 END)
    / NULLIF(SUM(CASE WHEN IFNULL(META_IS_FREE_TRIP,FALSE)=TRUE THEN 0 ELSE IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 END),0)*100, 1) AS MTD_DQR_PCT,
  ROUND(SUM(CASE WHEN bm_model_type='OWNED' AND META_SERVICEDETAILS_SERVICETYPE IN('ROAD_AMBULANCE','DEAD_BODY_ROAD_TRANSPORT')
    AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END),0) AS MTD_OWN_ROAD_REV,
  ROUND(SUM(CASE WHEN META_SERVICEDETAILS_SERVICETYPE IN('ROAD_AMBULANCE','DEAD_BODY_ROAD_TRANSPORT')
    AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END),0) AS MTD_ROAD_REV,
  ROUND(
    SUM(CASE WHEN bm_model_type='OWNED' AND META_SERVICEDETAILS_SERVICETYPE IN('ROAD_AMBULANCE','DEAD_BODY_ROAD_TRANSPORT')
      AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END)
    / NULLIF(SUM(CASE WHEN META_SERVICEDETAILS_SERVICETYPE IN('ROAD_AMBULANCE','DEAD_BODY_ROAD_TRANSPORT')
      AND IFNULL(META_IS_FREE_TRIP,FALSE)<>TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 ELSE 0 END),0)*100, 1) AS MTD_OWN_ROAD_PCT,
  COUNT(CASE WHEN fin_date='${today}' THEN order_id END) AS TODAY_TRIPS,
  ROUND(SUM(CASE WHEN fin_date='${today}' THEN CASE WHEN IFNULL(META_IS_FREE_TRIP,FALSE)=TRUE THEN 0
    ELSE IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 END ELSE 0 END),0) AS TODAY_REV,
  COUNT(CASE WHEN fin_date='${yesterday}' AND fin_time<='${currentISTTime}' THEN order_id END) AS YDAY_TRIPS,
  ROUND(SUM(CASE WHEN fin_date='${yesterday}' AND fin_time<='${currentISTTime}' THEN CASE WHEN IFNULL(META_IS_FREE_TRIP,FALSE)=TRUE THEN 0
    ELSE IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT,0)/100 END ELSE 0 END),0) AS YDAY_REV
FROM base
GROUP BY CITY, AGENT_EMAIL, LOB
HAVING MTD_TRIPS_DELIVERED > 0
ORDER BY MTD_REV DESC NULLS LAST`;
}

// ============================================================
// FINANCE ANALYTICS - FUNNEL VIEW (Booking Stage)
// Groups by Hospital, Provider Type, Service Type
// Shows revenue projection at booking stage
// ============================================================
export function buildFinanceAnalyticsFunnelQuery(mtdStart, mtdEnd, today, yesterday, currentISTTime) {
  return `
WITH base AS (
  SELECT
    n.NAME AS HOSPITAL,
    CASE WHEN n.SITE_TYPE_DESC = 'DIGITAL' THEN 'DIGITAL' ELSE UPPER(TRIM(n.CITY)) END AS CITY,
    COALESCE(bo.ASSIGNMENT_PROVIDER_TYPE, 'UNKNOWN') AS PROVIDER_TYPE,
    COALESCE(bo.META_SERVICEDETAILS_SERVICETYPE, 'UNKNOWN') AS SERVICE_TYPE,
    bo.ORDER_ID,
    bo.META_ORDER_TYPE,
    bo.META_ORDER_STATUS,
    bo.META_IS_FREE_TRIP,
    bo.META_IS_BILL_TO_PATIENT,
    bo.PAYMENTS_TOTAL_ORDER_AMOUNT,
    bo.PAYMENTS_MARGIN,
    DATE(CONVERT_TIMEZONE('UTC','Asia/Kolkata', bo.META_CREATED_AT_TIMESTAMP)) AS created_date,
    TIME(CONVERT_TIMEZONE('UTC','Asia/Kolkata', bo.META_CREATED_AT_TIMESTAMP)) AS created_time
  FROM BLADE.CORE.RED_BLADE_ORDERS_FINAL bo
  LEFT JOIN BLADE.CORE.BLADE_ORGANIZATION_ENTITIES_NEW_FLATTENED n
    ON bo.META_SITE_ID = n.SITE_ID
  WHERE bo.META_ORG_ID = '${ORG_ID}'
    AND bo.META_ORDER_TYPE = 'BOOKING'
    AND bo.META_ORDER_STATUS NOT IN ('CANCELLED', 'DISPUTED')
    AND IFNULL(bo.META_IS_FREE_TRIP, FALSE) != TRUE
    AND COALESCE(bo.META_ORDER_TYPE, '') != 'TEST'
    AND IFNULL(bo.META_SERVICEDETAILS_SERVICETYPE, '') NOT IN ('AIR_AMBULANCE', 'DEAD_BODY_AIR_CARGO')
    AND DATE(CONVERT_TIMEZONE('UTC','Asia/Kolkata', bo.META_CREATED_AT_TIMESTAMP))
        BETWEEN '${mtdStart}' AND '${mtdEnd}'
)
SELECT
  HOSPITAL,
  CITY,
  PROVIDER_TYPE,
  SERVICE_TYPE,
  COUNT(*) AS TOTAL_BOOKINGS,
  ROUND(SUM(CASE WHEN IFNULL(META_IS_FREE_TRIP, FALSE) != TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT, 0) / 100 ELSE 0 END), 0) AS TOTAL_REV,
  ROUND(SUM(IFNULL(PAYMENTS_MARGIN, 0) / 100), 0) AS MARGIN_AMT,
  ROUND(
    SUM(IFNULL(PAYMENTS_MARGIN, 0) / 100) /
    NULLIF(SUM(CASE WHEN IFNULL(META_IS_FREE_TRIP, FALSE) != TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT, 0) / 100 ELSE 0 END), 0) * 100,
    1
  ) AS MARGIN_PCT,
  ROUND(SUM(CASE WHEN META_IS_BILL_TO_PATIENT != TRUE AND IFNULL(META_IS_FREE_TRIP, FALSE) != TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT, 0) / 100 ELSE 0 END), 0) AS BILL_TO_CLIENT_REV,
  ROUND(SUM(CASE WHEN META_IS_BILL_TO_PATIENT = TRUE AND IFNULL(META_IS_FREE_TRIP, FALSE) != TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT, 0) / 100 ELSE 0 END), 0) AS DIRECT_PAY_REV,
  COUNT(CASE WHEN META_IS_BILL_TO_PATIENT != TRUE THEN ORDER_ID END) AS BILL_TO_CLIENT_COUNT,
  COUNT(CASE WHEN META_IS_BILL_TO_PATIENT = TRUE THEN ORDER_ID END) AS DIRECT_PAY_COUNT,
  COUNT(CASE WHEN created_date = '${today}' THEN ORDER_ID END) AS TODAY_BOOKINGS,
  ROUND(SUM(CASE WHEN created_date = '${today}' AND IFNULL(META_IS_FREE_TRIP, FALSE) != TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT, 0) / 100 ELSE 0 END), 0) AS TODAY_REV,
  COUNT(CASE WHEN created_date = '${yesterday}' AND created_time <= '${currentISTTime}' THEN ORDER_ID END) AS YDAY_BOOKINGS,
  ROUND(SUM(CASE WHEN created_date = '${yesterday}' AND created_time <= '${currentISTTime}' AND IFNULL(META_IS_FREE_TRIP, FALSE) != TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT, 0) / 100 ELSE 0 END), 0) AS YDAY_REV
FROM base
GROUP BY HOSPITAL, CITY, PROVIDER_TYPE, SERVICE_TYPE
HAVING COUNT(*) > 0
ORDER BY TOTAL_REV DESC NULLS LAST`;
}

// ============================================================
// FINANCE ANALYTICS - FINANCE VIEW (Delivered/Accrual)
// Groups by Hospital, Provider Type, Service Type
// Shows actual delivered/accrual revenue based on fulfillment date
// ============================================================
export function buildFinanceAnalyticsFinanceQuery(mtdStart, mtdEnd, today, yesterday, currentISTTime) {
  return `
WITH base AS (
  SELECT
    n.NAME AS HOSPITAL,
    CASE WHEN n.SITE_TYPE_DESC = 'DIGITAL' THEN 'DIGITAL' ELSE UPPER(TRIM(n.CITY)) END AS CITY,
    COALESCE(bo.ASSIGNMENT_PROVIDER_TYPE, 'UNKNOWN') AS PROVIDER_TYPE,
    COALESCE(bo.META_SERVICEDETAILS_SERVICETYPE, 'UNKNOWN') AS SERVICE_TYPE,
    bo.ORDER_ID,
    bo.META_ORDER_TYPE,
    bo.META_ORDER_STATUS,
    bo.META_IS_FREE_TRIP,
    bo.META_IS_BILL_TO_PATIENT,
    bo.PAYMENTS_TOTAL_ORDER_AMOUNT,
    bo.PAYMENTS_MARGIN,
    COALESCE(
      TO_DATE(CONVERT_TIMEZONE('UTC','Asia/Kolkata', bo.assignment_reacheddropoffat_timestamp)),
      TO_DATE(bo.FULFILLMENT_FULFILLED_AT_IST)
    ) AS fin_date,
    TIME(COALESCE(
      CONVERT_TIMEZONE('UTC','Asia/Kolkata', bo.assignment_reacheddropoffat_timestamp),
      bo.FULFILLMENT_FULFILLED_AT_IST
    )) AS fin_time
  FROM BLADE.CORE.RED_BLADE_ORDERS_FINAL bo
  LEFT JOIN BLADE.CORE.BLADE_ORGANIZATION_ENTITIES_NEW_FLATTENED n
    ON bo.META_SITE_ID = n.SITE_ID
  WHERE bo.META_ORG_ID = '${ORG_ID}'
    AND bo.META_ORDER_TYPE = 'BOOKING'
    AND bo.META_ORDER_STATUS NOT IN ('CANCELLED', 'DISPUTED')
    AND IFNULL(bo.META_IS_FREE_TRIP, FALSE) != TRUE
    AND COALESCE(bo.META_ORDER_TYPE, '') != 'TEST'
    AND IFNULL(bo.META_SERVICEDETAILS_SERVICETYPE, '') NOT IN ('AIR_AMBULANCE', 'DEAD_BODY_AIR_CARGO')
    AND COALESCE(
      TO_DATE(CONVERT_TIMEZONE('UTC','Asia/Kolkata', bo.assignment_reacheddropoffat_timestamp)),
      TO_DATE(bo.FULFILLMENT_FULFILLED_AT_IST)
    ) BETWEEN '${mtdStart}' AND '${mtdEnd}'
)
SELECT
  HOSPITAL,
  CITY,
  PROVIDER_TYPE,
  SERVICE_TYPE,
  COUNT(*) AS TOTAL_TRIPS,
  ROUND(SUM(CASE WHEN IFNULL(META_IS_FREE_TRIP, FALSE) != TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT, 0) / 100 ELSE 0 END), 0) AS TOTAL_REV,
  ROUND(SUM(IFNULL(PAYMENTS_MARGIN, 0) / 100), 0) AS MARGIN_AMT,
  ROUND(
    SUM(IFNULL(PAYMENTS_MARGIN, 0) / 100) /
    NULLIF(SUM(CASE WHEN IFNULL(META_IS_FREE_TRIP, FALSE) != TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT, 0) / 100 ELSE 0 END), 0) * 100,
    1
  ) AS MARGIN_PCT,
  ROUND(SUM(CASE WHEN META_IS_BILL_TO_PATIENT != TRUE AND IFNULL(META_IS_FREE_TRIP, FALSE) != TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT, 0) / 100 ELSE 0 END), 0) AS BILL_TO_CLIENT_REV,
  ROUND(SUM(CASE WHEN META_IS_BILL_TO_PATIENT = TRUE AND IFNULL(META_IS_FREE_TRIP, FALSE) != TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT, 0) / 100 ELSE 0 END), 0) AS DIRECT_PAY_REV,
  COUNT(CASE WHEN META_IS_BILL_TO_PATIENT != TRUE THEN ORDER_ID END) AS BILL_TO_CLIENT_COUNT,
  COUNT(CASE WHEN META_IS_BILL_TO_PATIENT = TRUE THEN ORDER_ID END) AS DIRECT_PAY_COUNT,
  COUNT(CASE WHEN fin_date = '${today}' THEN ORDER_ID END) AS TODAY_TRIPS,
  ROUND(SUM(CASE WHEN fin_date = '${today}' AND IFNULL(META_IS_FREE_TRIP, FALSE) != TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT, 0) / 100 ELSE 0 END), 0) AS TODAY_REV,
  COUNT(CASE WHEN fin_date = '${yesterday}' AND fin_time <= '${currentISTTime}' THEN ORDER_ID END) AS YDAY_TRIPS,
  ROUND(SUM(CASE WHEN fin_date = '${yesterday}' AND fin_time <= '${currentISTTime}' AND IFNULL(META_IS_FREE_TRIP, FALSE) != TRUE THEN IFNULL(PAYMENTS_TOTAL_ORDER_AMOUNT, 0) / 100 ELSE 0 END), 0) AS YDAY_REV
FROM base
GROUP BY HOSPITAL, CITY, PROVIDER_TYPE, SERVICE_TYPE
HAVING COUNT(*) > 0
ORDER BY TOTAL_REV DESC NULLS LAST`;
}
